# Generated by Django 5.2.9 on 2025-12-26 12:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_no', models.CharField(max_length=50, unique=True, verbose_name='领料单号')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('issued', '已发料'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='发料时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='发料人')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '领料单',
                'verbose_name_plural': '领料单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='需求数量')),
                ('issued_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实发数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material', verbose_name='原料')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.materialrequisition', verbose_name='领料单')),
            ],
            options={
                'verbose_name': '领料单明细',
                'verbose_name_plural': '领料单明细',
            },
        ),
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=50, unique=True, verbose_name='任务单号')),
                ('required_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='需求数量')),
                ('completed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='完成数量')),
                ('status', models.CharField(choices=[('pending', '待接收'), ('received', '已接收'), ('material_preparing', '备料中'), ('in_production', '生产中'), ('qc_checking', '质检中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='接收时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_tasks', to='sales.salesorder', verbose_name='关联订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='产品')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_tasks', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '生产任务单',
                'verbose_name_plural': '生产任务单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requisitions', to='production.productiontask', verbose_name='生产任务'),
        ),
        migrations.CreateModel(
            name='QCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, verbose_name='批次号')),
                ('inspected_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='抽检数量')),
                ('qualified_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='合格数量')),
                ('unqualified_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='不合格数量')),
                ('qualification_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='合格率(%)')),
                ('result', models.CharField(choices=[('qualified', '合格'), ('unqualified', '不合格'), ('rework', '返工')], max_length=20, verbose_name='质检结果')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_records', to=settings.AUTH_USER_MODEL, verbose_name='质检员')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_records', to='production.productiontask', verbose_name='生产任务')),
            ],
            options={
                'verbose_name': '质检记录',
                'verbose_name_plural': '质检记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinishedProductInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_no', models.CharField(max_length=50, unique=True, verbose_name='入库单号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='入库数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbounds', to='production.productiontask', verbose_name='生产任务')),
                ('qc_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.qcrecord', verbose_name='质检记录')),
            ],
            options={
                'verbose_name': '成品入库单',
                'verbose_name_plural': '成品入库单',
                'ordering': ['-created_at'],
            },
        ),
    ]
