# Generated by Django 6.0.1 on 2026-01-10 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequisition',
            name='terminate_reason',
            field=models.TextField(blank=True, verbose_name='终结原因'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='终结时间'),
        ),
        migrations.AddField(
            model_name='materialrequisition',
            name='terminated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='终结人'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='terminate_reason',
            field=models.TextField(blank=True, verbose_name='终结原因'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='终结时间'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='terminated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_tasks', to=settings.AUTH_USER_MODEL, verbose_name='终结人'),
        ),
        migrations.AlterField(
            model_name='materialrequisition',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('issued', '已发料'), ('cancelled', '已取消'), ('terminated', '已终结')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='status',
            field=models.CharField(choices=[('pending', '待接收'), ('received', '已接收'), ('material_preparing', '备料中'), ('in_production', '生产中'), ('qc_checking', '质检中'), ('completed', '已完成'), ('cancelled', '已取消'), ('terminated', '已终结')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
