# Generated by Django 5.2.9 on 2026-01-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_materialrequisition_terminate_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='planned_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='计划完成日期'),
        ),
    ]
