# Generated by Django 5.2.9 on 2026-01-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productiontask_planned_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiontask',
            name='status',
            field=models.CharField(choices=[('pending', '待接收'), ('material_insufficient', '原料不足'), ('received', '已接收'), ('material_preparing', '备料中'), ('in_production', '生产中'), ('qc_checking', '质检中'), ('completed', '已完成'), ('cancelled', '已取消'), ('terminated', '已终结')], default='pending', max_length=25, verbose_name='状态'),
        ),
    ]
