# Generated by Django 6.0.1 on 2026-01-12 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_productiontask_status'),
        ('sales', '0008_alter_salesorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontask',
            name='production_type',
            field=models.CharField(choices=[('order', '订单生产'), ('stock', '备货生产')], default='order', max_length=10, verbose_name='生产类型'),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_tasks', to='sales.salesorder', verbose_name='关联订单'),
        ),
    ]
