# Generated by Django 4.2.27 on 2026-02-01 14:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_add_adjustment_type_and_unit_change_transaction'),
        ('production', '0005_productiontask_production_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequisitionItemBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_locked', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='锁定数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_allocations', to='inventory.batch', verbose_name='批次')),
                ('requisition_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='production.materialrequisitionitem', verbose_name='领料明细')),
            ],
            options={
                'verbose_name': '领料批次锁定',
                'verbose_name_plural': '领料批次锁定',
                'ordering': ['requisition_item', 'batch'],
            },
        ),
    ]
