# Generated by Django 4.2.27 on 2026-02-07 11:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_add_other_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0007_dual_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproductinbound',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='入库数量（基础单位）'),
        ),
        migrations.AlterField(
            model_name='materialrequisitionitem',
            name='issued_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实发数量（基础单位）'),
        ),
        migrations.AlterField(
            model_name='materialrequisitionitem',
            name='required_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='需求数量（基础单位）'),
        ),
        migrations.AlterField(
            model_name='materialrequisitionitembatch',
            name='quantity_locked',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='锁定数量（基础单位）'),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='completed_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='完成数量（基础单位）'),
        ),
        migrations.AlterField(
            model_name='productiontask',
            name='required_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='需求数量（基础单位）'),
        ),
        migrations.CreateModel(
            name='TaskMaterialOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='单位产品用量')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='调整说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material', verbose_name='原料')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_overrides', to='production.productiontask', verbose_name='生产任务')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unit', verbose_name='用量单位')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '任务物料用量覆盖',
                'verbose_name_plural': '任务物料用量覆盖',
                'unique_together': {('task', 'material')},
            },
        ),
    ]
