# Generated by Django 5.2.9 on 2025-12-26 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('license_no', models.CharField(max_length=50, unique=True, verbose_name='驾照号码')),
                ('license_type', models.CharField(max_length=20, verbose_name='驾照类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '司机',
                'verbose_name_plural': '司机',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=20, unique=True, verbose_name='车牌号')),
                ('vehicle_type', models.CharField(choices=[('truck', '货车'), ('van', '面包车'), ('pickup', '皮卡')], max_length=20, verbose_name='车辆类型')),
                ('model', models.CharField(max_length=100, verbose_name='车型')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='载重(吨)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_no', models.CharField(max_length=50, unique=True, verbose_name='发货单号')),
                ('freight_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('status', models.CharField(choices=[('pending', '待发货'), ('loading', '装车中'), ('shipped', '已发货'), ('delivered', '已送达')], default='pending', max_length=20, verbose_name='状态')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.driver', verbose_name='司机')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='sales.salesorder', verbose_name='订单')),
                ('shipped_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipped_shipments', to=settings.AUTH_USER_MODEL, verbose_name='发货人')),
                ('shipping_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='sales.shippingnotice', verbose_name='发货通知单')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.vehicle', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '发货单',
                'verbose_name_plural': '发货单',
                'ordering': ['-created_at'],
            },
        ),
    ]
