# Generated by Django 6.0.1 on 2026-01-10 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='收货时间'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_shipments', to=settings.AUTH_USER_MODEL, verbose_name='回执录入人'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_remark',
            field=models.TextField(blank=True, verbose_name='回执备注'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='收货人姓名'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='收货人电话'),
        ),
    ]
