# Generated by Django 6.0.1 on 2026-01-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_shipment_delivered_at_shipment_delivered_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-created_at'], 'verbose_name': '司机', 'verbose_name_plural': '司机'},
        ),
        migrations.AddField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='drivers', to='logistics.vehicle', verbose_name='相关车辆'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='驾照号码'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='驾照类型'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='联系方式'),
        ),
    ]
