# Generated by Django 6.0.1 on 2026-01-13 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_driver_options_driver_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicles',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='logistics.driver', verbose_name='司机'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_no',
            field=models.CharField(max_length=20, verbose_name='车牌号'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('truck', '货车'), ('van', '面包车'), ('pickup', '皮卡')], max_length=20, verbose_name='车辆款式'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('driver', 'plate_no')},
        ),
    ]
