# Generated by Django 6.0.1 on 2026-01-13 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_driver_vehicles_vehicle_driver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shipment_images/%Y/%m/%d/', verbose_name='图片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='图片说明')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='logistics.shipment', verbose_name='发货单')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_shipment_images', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '发货回执图片',
                'verbose_name_plural': '发货回执图片',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
