# Generated by Django 6.0.1 on 2026-01-17 07:58

import django.db.models.deletion
from django.db import migrations, models


def copy_shipping_notice_data(apps, schema_editor):
    """将数据从 sales.ShippingNotice 复制到 logistics.ShippingNotice"""
    # 获取旧模型和新模型
    OldShippingNotice = apps.get_model('sales', 'ShippingNotice')
    NewShippingNotice = apps.get_model('logistics', 'ShippingNotice')
    Shipment = apps.get_model('logistics', 'Shipment')
    
    # 创建 ID 映射字典
    id_mapping = {}
    
    # 复制所有 ShippingNotice 数据
    for old_notice in OldShippingNotice.objects.all():
        new_notice = NewShippingNotice.objects.create(
            notice_no=old_notice.notice_no,
            status=old_notice.status,
            created_at=old_notice.created_at,
            order_id=old_notice.order_id,
        )
        id_mapping[old_notice.id] = new_notice.id
    
    # 更新 Shipment 表中的外键引用
    for shipment in Shipment.objects.all():
        if shipment.shipping_notice_id and shipment.shipping_notice_id in id_mapping:
            shipment.shipping_notice_id = id_mapping[shipment.shipping_notice_id]
            shipment.save(update_fields=['shipping_notice_id'])


def reverse_copy_shipping_notice_data(apps, schema_editor):
    """反向迁移：将数据从 logistics.ShippingNotice 复制回 sales.ShippingNotice"""
    OldShippingNotice = apps.get_model('sales', 'ShippingNotice')
    NewShippingNotice = apps.get_model('logistics', 'ShippingNotice')
    Shipment = apps.get_model('logistics', 'Shipment')
    
    # 创建 ID 映射字典
    id_mapping = {}
    
    # 复制所有 ShippingNotice 数据
    for new_notice in NewShippingNotice.objects.all():
        old_notice = OldShippingNotice.objects.create(
            notice_no=new_notice.notice_no,
            status=new_notice.status,
            created_at=new_notice.created_at,
            order_id=new_notice.order_id,
        )
        id_mapping[new_notice.id] = old_notice.id
    
    # 更新 Shipment 表中的外键引用
    for shipment in Shipment.objects.all():
        if shipment.shipping_notice_id and shipment.shipping_notice_id in id_mapping:
            shipment.shipping_notice_id = id_mapping[shipment.shipping_notice_id]
            shipment.save(update_fields=['shipping_notice_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_shipmentimage'),
        ('sales', '0009_salesorderitembatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_no', models.CharField(max_length=50, unique=True, verbose_name='通知单号')),
                ('status', models.CharField(choices=[('pending', '待发货'), ('shipped', '已发货')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_notices', to='sales.salesorder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '发货通知单',
                'verbose_name_plural': '发货通知单',
                'ordering': ['-created_at'],
            },
        ),
        # 先复制数据
        migrations.RunPython(copy_shipping_notice_data, reverse_copy_shipping_notice_data),
        # 然后修改外键
        migrations.AlterField(
            model_name='shipment',
            name='shipping_notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='logistics.shippingnotice', verbose_name='发货通知单'),
        ),
    ]
