# Generated by Django 5.2.9 on 2026-01-09 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='退回原因'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退回时间'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_orders', to=settings.AUTH_USER_MODEL, verbose_name='退回人'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已审核'), ('rejected', '已退回'), ('in_production', '生产中'), ('ready_to_ship', '待发货'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
