# Generated by Django 5.2.9 on 2026-01-09 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesorder_reject_reason_salesorder_rejected_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='warehouse_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='库存审批时间'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='warehouse_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_approved_orders', to=settings.AUTH_USER_MODEL, verbose_name='库存审批人'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='销售审批时间'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL, verbose_name='销售审批人'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('pending', '待销售审批'), ('approved', '销售已审批'), ('warehouse_pending', '待库存审批'), ('warehouse_approved', '库存已审批'), ('rejected', '已退回'), ('in_production', '生产中'), ('ready_to_ship', '待发货'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
