# Generated by Django 6.0.1 on 2026-01-10 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_salesorder_warehouse_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='warehouse_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='库存确认时间'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='warehouse_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_confirmed_orders', to=settings.AUTH_USER_MODEL, verbose_name='库存确认人'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('pending', '待销售审批'), ('approved', '销售已审批'), ('ceo_pending', '待总经理审批'), ('ceo_approved', '总经理已审批'), ('warehouse_pending', '待库存确认'), ('warehouse_confirmed', '库存已确认'), ('rejected', '已退回'), ('in_production', '生产中'), ('ready_to_ship', '待发货'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
