# Generated by Django 5.2.9 on 2026-01-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_salesorder_warehouse_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='交付日期'),
        ),
    ]
