# Generated by Django 6.0.1 on 2026-01-12 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salesorder_delivery_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-created_at'], 'verbose_name': '产品订单', 'verbose_name_plural': '产品订单'},
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批时间'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('ceo_pending', '待总经理审批'), ('ceo_approved', '总经理已审批'), ('rejected', '已退回'), ('in_production', '生产中'), ('ready_to_ship', '待发货'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消'), ('terminated', '已终结')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
