# Generated by Django 6.0.1 on 2026-01-12 12:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_batch_stocktransaction_batch_and_more'),
        ('sales', '0008_alter_salesorder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderItemBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='分配数量')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.batch', verbose_name='批次')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='sales.salesorderitem', verbose_name='订单明细')),
            ],
            options={
                'verbose_name': '订单明细批次分配',
                'verbose_name_plural': '订单明细批次分配',
                'unique_together': {('order_item', 'batch')},
            },
        ),
    ]
