# Generated by Django 6.0.1 on 2026-01-17 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_customer_data(apps, schema_editor):
    """将数据从 inventory.Customer 复制到 sales.Customer"""
    # 获取旧模型和新模型
    OldCustomer = apps.get_model('inventory', 'Customer')
    NewCustomer = apps.get_model('sales', 'Customer')
    SalesOrder = apps.get_model('sales', 'SalesOrder')
    CustomerTransfer = apps.get_model('sales', 'CustomerTransfer')
    
    # 创建 ID 映射字典
    id_mapping = {}
    
    # 复制所有 Customer 数据
    for old_customer in OldCustomer.objects.all():
        # 使用 getattr 安全获取字段值，如果字段不存在则使用默认值
        new_customer = NewCustomer.objects.create(
            name=old_customer.name,
            contact_person=old_customer.contact_person,
            phone=old_customer.phone,
            address=old_customer.address,
            credit_level=old_customer.credit_level,
            created_by_id=getattr(old_customer, 'created_by_id', None),
            created_at=old_customer.created_at,
            updated_at=old_customer.updated_at,
            edit_status=getattr(old_customer, 'edit_status', 'none'),
            edit_pending_data=getattr(old_customer, 'edit_pending_data', ''),
            edit_reason=getattr(old_customer, 'edit_reason', ''),
            edit_requested_at=getattr(old_customer, 'edit_requested_at', None),
            edit_approved_at=getattr(old_customer, 'edit_approved_at', None),
            edit_reject_reason=getattr(old_customer, 'edit_reject_reason', ''),
            delete_status=getattr(old_customer, 'delete_status', 'none'),
            delete_reason=getattr(old_customer, 'delete_reason', ''),
            delete_requested_at=getattr(old_customer, 'delete_requested_at', None),
            delete_approved_at=getattr(old_customer, 'delete_approved_at', None),
            delete_reject_reason=getattr(old_customer, 'delete_reject_reason', ''),
            is_deleted=getattr(old_customer, 'is_deleted', False),
            edit_requested_by_id=getattr(old_customer, 'edit_requested_by_id', None),
            edit_approved_by_id=getattr(old_customer, 'edit_approved_by_id', None),
            delete_requested_by_id=getattr(old_customer, 'delete_requested_by_id', None),
            delete_approved_by_id=getattr(old_customer, 'delete_approved_by_id', None),
        )
        id_mapping[old_customer.id] = new_customer.id
    
    # 更新 SalesOrder 表中的外键引用
    for order in SalesOrder.objects.all():
        if order.customer_id and order.customer_id in id_mapping:
            order.customer_id = id_mapping[order.customer_id]
            order.save(update_fields=['customer_id'])
    
    # 复制 CustomerTransfer 数据
    OldCustomerTransfer = apps.get_model('inventory', 'CustomerTransfer')
    for old_transfer in OldCustomerTransfer.objects.all():
        if old_transfer.customer_id in id_mapping:
            CustomerTransfer.objects.create(
                customer_id=id_mapping[old_transfer.customer_id],
                from_user_id=old_transfer.from_user_id,
                to_user_id=old_transfer.to_user_id,
                transferred_by_id=old_transfer.transferred_by_id,
                transferred_at=old_transfer.transferred_at,
                remark=old_transfer.remark,
            )


def reverse_copy_customer_data(apps, schema_editor):
    """反向迁移：将数据从 sales.Customer 复制回 inventory.Customer"""
    OldCustomer = apps.get_model('inventory', 'Customer')
    NewCustomer = apps.get_model('sales', 'Customer')
    SalesOrder = apps.get_model('sales', 'SalesOrder')
    
    # 创建 ID 映射字典
    id_mapping = {}
    
    # 复制所有 Customer 数据
    for new_customer in NewCustomer.objects.all():
        # 只复制 inventory.Customer 表中存在的字段
        customer_data = {
            'name': new_customer.name,
            'contact_person': new_customer.contact_person,
            'phone': new_customer.phone,
            'address': new_customer.address,
            'credit_level': new_customer.credit_level,
            'created_at': new_customer.created_at,
            'updated_at': new_customer.updated_at,
        }
        # 只添加存在的字段
        if hasattr(OldCustomer, 'created_by'):
            customer_data['created_by_id'] = new_customer.created_by_id
        if hasattr(OldCustomer, 'edit_status'):
            customer_data['edit_status'] = new_customer.edit_status
            customer_data['edit_pending_data'] = new_customer.edit_pending_data
            customer_data['edit_reason'] = new_customer.edit_reason
            customer_data['edit_requested_at'] = new_customer.edit_requested_at
            customer_data['edit_approved_at'] = new_customer.edit_approved_at
            customer_data['edit_reject_reason'] = new_customer.edit_reject_reason
            customer_data['edit_requested_by_id'] = new_customer.edit_requested_by_id
            customer_data['edit_approved_by_id'] = new_customer.edit_approved_by_id
        if hasattr(OldCustomer, 'delete_status'):
            customer_data['delete_status'] = new_customer.delete_status
            customer_data['delete_reason'] = new_customer.delete_reason
            customer_data['delete_requested_at'] = new_customer.delete_requested_at
            customer_data['delete_approved_at'] = new_customer.delete_approved_at
            customer_data['delete_reject_reason'] = new_customer.delete_reject_reason
            customer_data['delete_requested_by_id'] = new_customer.delete_requested_by_id
            customer_data['delete_approved_by_id'] = new_customer.delete_approved_by_id
        
        old_customer = OldCustomer.objects.create(**customer_data)
        id_mapping[new_customer.id] = old_customer.id
    
    # 更新 SalesOrder 表中的外键引用
    for order in SalesOrder.objects.all():
        if order.customer_id and order.customer_id in id_mapping:
            order.customer_id = id_mapping[order.customer_id]
            order.save(update_fields=['customer_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_shippingnotice_alter_shipment_shipping_notice'),
        ('sales', '0009_salesorderitembatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='客户名称')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.TextField(verbose_name='地址')),
                ('credit_level', models.CharField(choices=[('A', 'A级（优秀）'), ('B', 'B级（良好）'), ('C', 'C级（一般）'), ('D', 'D级（较差）')], default='C', max_length=1, verbose_name='信用等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('edit_status', models.CharField(choices=[('none', '无编辑申请'), ('pending', '待审批'), ('approved', '已审批'), ('rejected', '已拒绝')], default='none', max_length=20, verbose_name='编辑审批状态')),
                ('edit_pending_data', models.TextField(blank=True, verbose_name='待审批编辑数据')),
                ('edit_reason', models.TextField(blank=True, verbose_name='编辑原因')),
                ('edit_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='编辑申请时间')),
                ('edit_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='编辑审批时间')),
                ('edit_reject_reason', models.TextField(blank=True, verbose_name='编辑拒绝原因')),
                ('delete_status', models.CharField(choices=[('none', '无删除申请'), ('pending', '待审批'), ('approved', '已审批'), ('rejected', '已拒绝')], default='none', max_length=20, verbose_name='删除审批状态')),
                ('delete_reason', models.TextField(blank=True, verbose_name='删除原因')),
                ('delete_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='删除申请时间')),
                ('delete_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='删除审批时间')),
                ('delete_reject_reason', models.TextField(blank=True, verbose_name='删除拒绝原因')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除（软删除）')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('delete_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_customer_deletes', to=settings.AUTH_USER_MODEL, verbose_name='删除审批人')),
                ('delete_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_delete_requests', to=settings.AUTH_USER_MODEL, verbose_name='删除申请人')),
                ('edit_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_customer_edits', to=settings.AUTH_USER_MODEL, verbose_name='编辑审批人')),
                ('edit_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_edit_requests', to=settings.AUTH_USER_MODEL, verbose_name='编辑申请人')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField(auto_now_add=True, verbose_name='转移时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='sales.customer', verbose_name='客户')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from_customers', to=settings.AUTH_USER_MODEL, verbose_name='原负责人')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_to_customers', to=settings.AUTH_USER_MODEL, verbose_name='新负责人')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_transfers', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '客户转移记录',
                'verbose_name_plural': '客户转移记录',
                'ordering': ['-transferred_at'],
            },
        ),
        # 先复制数据
        migrations.RunPython(copy_customer_data, reverse_copy_customer_data),
        # 然后修改外键
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='客户'),
        ),
        migrations.DeleteModel(
            name='ShippingNotice',
        ),
    ]
