# Generated by Django 4.2.27 on 2026-02-08 06:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_add_other_unit_price'),
        ('sales', '0011_dual_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='reserve_inventory',
            field=models.BooleanField(default=True, verbose_name='锁定库存'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='display_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='销售业务数量'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='display_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_items', to='inventory.unit', verbose_name='销售业务单位'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='数量（基础单位）'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价（基础单位）'),
        ),
        migrations.AlterField(
            model_name='salesorderitembatch',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='分配数量（基础单位）'),
        ),
    ]
