# Generated by Django 4.2.27 on 2026-03-01 12:12

from django.db import migrations, models


def backfill_order_item_snapshots(apps, schema_editor):
    """为已提交的订单明细回填产品快照（名称、规格、单位），使历史订单展示不受后续产品修改影响。"""
    SalesOrderItem = apps.get_model('sales', 'SalesOrderItem')
    # 已提交：非待审批、非退回
    submitted_statuses = [
        'approved', 'ceo_pending', 'ceo_approved', 'in_production',
        'ready_to_ship', 'shipped', 'completed', 'cancelled', 'terminated',
    ]
    items = SalesOrderItem.objects.filter(
        order__status__in=submitted_statuses,
        product_id__isnull=False,
    ).select_related('product', 'order')
    for item in items:
        p = item.product
        item.product_name_snapshot = (p.name or '')[:200]
        item.product_specification_snapshot = getattr(p, 'specification', None) or ''
        item.display_unit_id = p.display_unit_id or p.base_unit_id
        item.save(update_fields=['product_name_snapshot', 'product_specification_snapshot', 'display_unit_id'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_salesorderitem_manual_batch_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='product_name_snapshot',
            field=models.CharField(blank=True, max_length=200, verbose_name='产品名称快照'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='product_specification_snapshot',
            field=models.TextField(blank=True, verbose_name='产品规格快照'),
        ),
        migrations.RunPython(backfill_order_item_snapshots, noop_reverse),
    ]
