# Generated by Django 5.2.9 on 2026-01-11 10:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_purchaseorder_purchaseorderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=50, unique=True, verbose_name='采购任务号')),
                ('supplier', models.CharField(max_length=200, verbose_name='供应商')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='采购总额')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('purchasing', '采购中'), ('completed', '已完成'), ('cancelled', '已取消'), ('terminated', '已终结')], default='pending', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('terminated_at', models.DateTimeField(blank=True, null=True, verbose_name='终结时间')),
                ('terminate_reason', models.TextField(blank=True, verbose_name='终结原因')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_tasks', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('terminated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_purchase_tasks', to=settings.AUTH_USER_MODEL, verbose_name='终结人')),
            ],
            options={
                'verbose_name': '采购任务',
                'verbose_name_plural': '采购任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='采购数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='小计')),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已收货数量')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material', verbose_name='物料')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchasetask', verbose_name='采购任务')),
            ],
            options={
                'verbose_name': '采购任务明细',
                'verbose_name_plural': '采购任务明细',
            },
        ),
    ]
