# Generated by Django 6.0.1 on 2026-01-14 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventory_unique_together_inventory_other_name_and_more'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetaskitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='物品名称'),
        ),
        migrations.AddField(
            model_name='purchasetaskitem',
            name='item_type',
            field=models.CharField(choices=[('material', '原料'), ('office', '办公用品'), ('other', '其它')], default='material', max_length=20, verbose_name='物品类型'),
        ),
        migrations.AddField(
            model_name='purchasetaskitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='purchasetaskitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.material', verbose_name='物料'),
        ),
    ]
