# Generated by Django 6.0.1 on 2026-01-17 08:29

import django.db.models.deletion
from django.db import migrations, models


def migrate_supplier_data(apps, schema_editor):
    """将 PurchaseTask.supplier 字符串转换为 Supplier 外键"""
    PurchaseTask = apps.get_model('purchase', 'PurchaseTask')
    Supplier = apps.get_model('purchase', 'Supplier')
    User = apps.get_model('auth', 'User')
    
    # 获取第一个用户作为默认创建人（如果存在）
    default_user = User.objects.first()
    if not default_user:
        # 如果没有用户，创建一个临时用户（不应该发生，但为了安全）
        return
    
    # 使用原始 SQL 查询获取所有任务的 supplier 字符串值
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("SELECT id, supplier FROM purchase_purchasetask")
        rows = cursor.fetchall()
        
        for task_id, supplier_name in rows:
            if not supplier_name:
                continue
                
            # 查找或创建 Supplier
            supplier, created = Supplier.objects.get_or_create(
                name=supplier_name,
                defaults={
                    'created_by_id': default_user.id,
                }
            )
            
            # 更新 task 的 supplier_new_id
            cursor.execute(
                "UPDATE purchase_purchasetask SET supplier_new_id = %s WHERE id = %s",
                [supplier.id, task_id]
            )


def reverse_migrate_supplier_data(apps, schema_editor):
    """反向迁移：将 Supplier 外键转换回字符串"""
    PurchaseTask = apps.get_model('purchase', 'PurchaseTask')
    Supplier = apps.get_model('purchase', 'Supplier')
    
    # 使用原始 SQL 查询获取所有任务的 supplier_new_id
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("SELECT id, supplier_new_id FROM purchase_purchasetask WHERE supplier_new_id IS NOT NULL")
        rows = cursor.fetchall()
        
        for task_id, supplier_id in rows:
            try:
                supplier = Supplier.objects.get(pk=supplier_id)
                # 更新 supplier 字段为字符串
                cursor.execute(
                    "UPDATE purchase_purchasetask SET supplier = %s WHERE id = %s",
                    [supplier.name, task_id]
                )
            except Supplier.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_supplier'),
    ]

    operations = [
        # 第一步：添加新的 supplier_id 字段（允许 null，临时字段）
        migrations.AddField(
            model_name='purchasetask',
            name='supplier_new',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.supplier', verbose_name='供应商'),
        ),
        # 第二步：复制数据
        migrations.RunPython(migrate_supplier_data, reverse_migrate_supplier_data),
        # 第三步：删除旧字段
        migrations.RemoveField(
            model_name='purchasetask',
            name='supplier',
        ),
        # 第四步：重命名新字段
        migrations.RenameField(
            model_name='purchasetask',
            old_name='supplier_new',
            new_name='supplier',
        ),
        # 第五步：设置字段为必填
        migrations.AlterField(
            model_name='purchasetask',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.supplier', verbose_name='供应商'),
        ),
        # 第六步：删除重复字段
        migrations.RemoveField(
            model_name='purchasetask',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='purchasetask',
            name='contact_phone',
        ),
    ]
