# Generated by Django 6.0.1 on 2026-01-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_remove_purchasetask_contact_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasetaskitem',
            name='received_quantity',
        ),
    ]
