# Generated by Django 5.2.8 on 2026-02-25 15:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_add_other_unit_price"),
        ("purchase", "0006_dual_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasetaskitem",
            name="display_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="采购业务数量",
            ),
        ),
        migrations.AlterField(
            model_name="purchasetaskitem",
            name="display_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_items",
                to="inventory.unit",
                verbose_name="采购业务单位",
            ),
        ),
        migrations.AlterField(
            model_name="purchasetaskitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="采购数量（基础单位）",
            ),
        ),
        migrations.AlterField(
            model_name="purchasetaskitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="单价（基础单位）"
            ),
        ),
    ]
