# Generated by Django 4.2.27 on 2026-03-01 00:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_add_other_unit_price'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='产品编码/SKU')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('category', models.CharField(choices=[('finished', '成品'), ('raw', '原料'), ('semi', '半成品'), ('other', '其它')], max_length=20, verbose_name='产品分类')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价（基础单位）')),
                ('specification', models.TextField(blank=True, default='', verbose_name='规格说明')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='售价（基础单位，仅成品）')),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='安全库存（基础单位）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_master_base', to='inventory.unit', verbose_name='基础单位')),
                ('display_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_master_display', to='inventory.unit', verbose_name='显示单位')),
            ],
            options={
                'verbose_name': '产品主数据',
                'verbose_name_plural': '产品主数据',
                'db_table': 'product_product',
                'ordering': ['category', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='用量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('component', models.ForeignKey(limit_choices_to=Q(category='raw') | Q(category='semi'), on_delete=django.db.models.deletion.PROTECT, related_name='bom_as_component', to='product.product', verbose_name='原料/半成品')),
                ('product', models.ForeignKey(limit_choices_to={'category': 'finished'}, on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='product.product', verbose_name='成品')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_bom_units', to='inventory.unit', verbose_name='用量单位')),
            ],
            options={
                'verbose_name': 'BOM 配方',
                'verbose_name_plural': 'BOM 配方',
                'db_table': 'product_bom',
                'ordering': ['product', 'component'],
                'unique_together': {('product', 'component')},
            },
        ),
    ]
