# Generated by Django 4.2.27 on 2026-03-01 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_finished_raw_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='component',
            field=models.ForeignKey(limit_choices_to=models.Q(('category', 'raw'), ('category', 'other'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='bom_as_component', to='product.product', verbose_name='原料/其他'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('finished', '成品'), ('raw', '原料'), ('other', '其他')], max_length=20, verbose_name='产品分类'),
        ),
    ]
