# Generated by Django 5.2.9 on 2026-01-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='权限代码')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('category', models.CharField(choices=[('sales', '销售权限'), ('inventory', '库存权限'), ('production', '生产权限'), ('logistics', '物流权限'), ('system', '系统权限')], max_length=20, verbose_name='权限分类')),
                ('description', models.TextField(blank=True, verbose_name='权限描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='accounts.permission', verbose_name='额外权限'),
        ),
    ]
