# Generated by Django 5.2.9 on 2025-12-26 12:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='客户名称')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('address', models.TextField(verbose_name='地址')),
                ('credit_level', models.CharField(choices=[('A', 'A级（优秀）'), ('B', 'B级（良好）'), ('C', 'C级（一般）'), ('D', 'D级（较差）')], default='C', max_length=1, verbose_name='信用等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '原料分类',
                'verbose_name_plural': '原料分类',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU编码')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('specification', models.TextField(blank=True, verbose_name='规格说明')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='安全库存')),
                ('unit', models.CharField(default='件', max_length=20, verbose_name='单位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '成品',
                'verbose_name_plural': '成品',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU编码')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('material_type', models.CharField(choices=[('raw', '原料'), ('auxiliary', '辅料'), ('tool', '工具'), ('office', '办公用品')], default='raw', max_length=20, verbose_name='类型')),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='安全库存')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.materialcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '原料',
                'verbose_name_plural': '原料',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_type', models.CharField(choices=[('product', '成品'), ('material', '原料')], max_length=20, verbose_name='库存类型')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.material', verbose_name='原料')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.product', verbose_name='成品')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'unique_together': {('inventory_type', 'material'), ('inventory_type', 'product')},
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale_out', '销售出库'), ('production_out', '生产领料出库'), ('production_in', '生产完工入库'), ('purchase_in', '采购入库'), ('adjustment', '库存调整')], max_length=20, verbose_name='变动类型')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('reference_no', models.CharField(blank=True, max_length=100, verbose_name='关联单号')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory', verbose_name='库存')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '库存变动记录',
                'verbose_name_plural': '库存变动记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='用量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material', verbose_name='原料')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='inventory.product', verbose_name='成品')),
            ],
            options={
                'verbose_name': 'BOM配方',
                'verbose_name_plural': 'BOM配方',
                'ordering': ['product', 'material'],
                'unique_together': {('product', 'material')},
            },
        ),
    ]
