# Generated by Django 5.2.9 on 2026-01-09 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '成品分类',
                'verbose_name_plural': '成品分类',
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(max_length=50, unique=True, verbose_name='申请单号')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前数量')),
                ('adjust_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='调整数量')),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='调整后数量')),
                ('reason', models.TextField(verbose_name='调整原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('rejected', '已拒绝'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('reject_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustment_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inventory_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory', verbose_name='库存')),
            ],
            options={
                'verbose_name': '库存调整申请',
                'verbose_name_plural': '库存调整申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productcategory', verbose_name='分类'),
        ),
    ]
