# Generated by Django 5.2.9 on 2026-01-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustmentrequest',
            name='adjust_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='调整单价'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentrequest',
            name='current_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='当前单价'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentrequest',
            name='new_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='调整后单价'),
        ),
    ]
