# Generated by Django 5.2.9 on 2026-01-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryadjustmentrequest_adjust_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='new_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='调整后单价'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='old_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='调整前单价'),
        ),
    ]
