# Generated by Django 6.0.1 on 2026-01-12 11:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stocktransaction_new_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=100, verbose_name='批次号')),
                ('batch_date', models.DateField(verbose_name='批次日期')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='批次单价')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='过期日期')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供应商')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.inventory', verbose_name='库存')),
            ],
            options={
                'verbose_name': '库存批次',
                'verbose_name_plural': '库存批次',
                'ordering': ['batch_date', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.batch', verbose_name='批次'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['inventory', 'batch_date'], name='inventory_b_invento_828a9f_idx'),
        ),
    ]
