# Generated by Django 6.0.1 on 2026-01-13 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_batch_stocktransaction_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delete_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除审批时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delete_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_customer_deletes', to=settings.AUTH_USER_MODEL, verbose_name='删除审批人'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delete_reason',
            field=models.TextField(blank=True, verbose_name='删除原因'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delete_reject_reason',
            field=models.TextField(blank=True, verbose_name='删除拒绝原因'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delete_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除申请时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delete_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_delete_requests', to=settings.AUTH_USER_MODEL, verbose_name='删除申请人'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delete_status',
            field=models.CharField(choices=[('none', '无删除申请'), ('pending', '待审批'), ('approved', '已审批'), ('rejected', '已拒绝')], default='none', max_length=20, verbose_name='删除审批状态'),
        ),
        migrations.AddField(
            model_name='customer',
            name='edit_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='编辑审批时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='edit_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_customer_edits', to=settings.AUTH_USER_MODEL, verbose_name='编辑审批人'),
        ),
        migrations.AddField(
            model_name='customer',
            name='edit_pending_data',
            field=models.TextField(blank=True, verbose_name='待审批编辑数据'),
        ),
        migrations.AddField(
            model_name='customer',
            name='edit_reason',
            field=models.TextField(blank=True, verbose_name='编辑原因'),
        ),
        migrations.AddField(
            model_name='customer',
            name='edit_reject_reason',
            field=models.TextField(blank=True, verbose_name='编辑拒绝原因'),
        ),
        migrations.AddField(
            model_name='customer',
            name='edit_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='编辑申请时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='edit_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_edit_requests', to=settings.AUTH_USER_MODEL, verbose_name='编辑申请人'),
        ),
        migrations.AddField(
            model_name='customer',
            name='edit_status',
            field=models.CharField(choices=[('none', '无编辑申请'), ('pending', '待审批'), ('approved', '已审批'), ('rejected', '已拒绝')], default='none', max_length=20, verbose_name='编辑审批状态'),
        ),
    ]
