# Generated by Django 6.0.1 on 2026-01-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_customer_created_by_customertransfer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='other_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='其它物品名称'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('product', '成品'), ('material', '原料'), ('other', '其它')], max_length=20, verbose_name='库存类型'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('inventory_type', 'product')), fields=('inventory_type', 'product'), name='unique_product_inventory'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('inventory_type', 'material')), fields=('inventory_type', 'material'), name='unique_material_inventory'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('inventory_type', 'other'), models.Q(('other_name', ''), _negated=True)), fields=('inventory_type', 'other_name'), name='unique_other_inventory'),
        ),
    ]
