# Generated by Django 6.0.1 on 2026-01-17 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventory_unique_together_inventory_other_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='locked_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='锁定数量'),
        ),
    ]
