# Generated by Django 6.0.1 on 2026-01-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_batch_locked_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delete_approved_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delete_requested_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='edit_approved_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='edit_requested_by',
        ),
        migrations.RemoveField(
            model_name='customertransfer',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customertransfer',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='customertransfer',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='customertransfer',
            name='transferred_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='material',
        ),
    ]
