# Generated by Django 4.2.27 on 2026-01-21 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_delete_customer_delete_customertransfer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='单位代码')),
                ('name', models.CharField(max_length=50, verbose_name='单位名称')),
                ('category', models.CharField(choices=[('weight', '重量'), ('length', '长度'), ('volume', '体积'), ('quantity', '数量'), ('packaging', '包装')], max_length=20, verbose_name='单位类别')),
                ('is_base', models.BooleanField(default=False, verbose_name='是否为基础计量单位')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '基础单位',
                'verbose_name_plural': '基础单位',
                'db_table': 'inventory_unit',
                'ordering': ['category', 'display_order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(default='kg', max_length=20, verbose_name='单位（显示单位）'),
        ),
        migrations.AddField(
            model_name='material',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='inventory.unit', verbose_name='基础单位'),
        ),
        migrations.CreateModel(
            name='MaterialPackagingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_unit_name', models.CharField(max_length=20, verbose_name='包装单位名称')),
                ('conversion_factor', models.DecimalField(decimal_places=4, help_text='1个包装单位 = 转换系数 个基础单位。例如：1袋=100kg，则系数为100', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='转换系数')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认包装单位')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_packaging_units', to='inventory.unit', verbose_name='基础单位')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_units', to='inventory.material', verbose_name='物料')),
            ],
            options={
                'verbose_name': '物料包装单位',
                'verbose_name_plural': '物料包装单位',
                'db_table': 'inventory_material_packaging_unit',
                'ordering': ['material', 'display_order', 'packaging_unit_name'],
                'unique_together': {('material', 'packaging_unit_name')},
            },
        ),
    ]
