# Generated by Django 4.2.27 on 2026-01-21 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0015_unit_alter_material_unit_material_base_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialUnitChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_unit', models.CharField(max_length=20, verbose_name='旧单位')),
                ('old_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='旧单价')),
                ('old_safety_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='旧安全库存')),
                ('new_unit', models.CharField(max_length=20, verbose_name='新单位')),
                ('new_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='新单价')),
                ('new_safety_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='新安全库存')),
                ('conversion_factor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='转换系数')),
                ('old_inventory_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='变更前库存数量')),
                ('new_inventory_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='变更后库存数量')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('reason', models.TextField(verbose_name='变更原因')),
                ('approval_status', models.CharField(choices=[('auto', '自动通过'), ('approved', '已审批'), ('rejected', '已拒绝')], default='auto', max_length=20, verbose_name='审批状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_unit_changes', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_unit_changes', to=settings.AUTH_USER_MODEL, verbose_name='变更人')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_change_history', to='inventory.material', verbose_name='物料')),
            ],
            options={
                'verbose_name': '物料单位变更历史',
                'verbose_name_plural': '物料单位变更历史',
                'db_table': 'inventory_material_unit_change_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
