# Generated by Django 4.2.27 on 2026-01-21 16:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0016_materialunitchangehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.unit', verbose_name='基础单位'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='件', max_length=20, verbose_name='单位（显示单位）'),
        ),
        migrations.CreateModel(
            name='ProductUnitChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_unit', models.CharField(max_length=20, verbose_name='旧单位')),
                ('old_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='旧单价')),
                ('old_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='旧售价')),
                ('old_safety_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='旧安全库存')),
                ('new_unit', models.CharField(max_length=20, verbose_name='新单位')),
                ('new_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='新单价')),
                ('new_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='新售价')),
                ('new_safety_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='新安全库存')),
                ('conversion_factor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='转换系数')),
                ('old_inventory_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='变更前库存数量')),
                ('new_inventory_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='变更后库存数量')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('reason', models.TextField(verbose_name='变更原因')),
                ('approval_status', models.CharField(choices=[('auto', '自动通过'), ('approved', '已审批'), ('rejected', '已拒绝')], default='auto', max_length=20, verbose_name='审批状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_product_unit_changes', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_unit_changes', to=settings.AUTH_USER_MODEL, verbose_name='变更人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_change_history', to='inventory.product', verbose_name='成品')),
            ],
            options={
                'verbose_name': '成品单位变更历史',
                'verbose_name_plural': '成品单位变更历史',
                'db_table': 'inventory_product_unit_change_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPackagingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_unit_name', models.CharField(max_length=20, verbose_name='包装单位名称')),
                ('conversion_factor', models.DecimalField(decimal_places=4, help_text='1个包装单位 = 转换系数 个基础单位。例如：1箱=12件，则系数为12', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='转换系数')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认包装单位')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_packaging_units', to='inventory.unit', verbose_name='基础单位')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_units', to='inventory.product', verbose_name='成品')),
            ],
            options={
                'verbose_name': '成品包装单位',
                'verbose_name_plural': '成品包装单位',
                'db_table': 'inventory_product_packaging_unit',
                'ordering': ['product', 'display_order', 'packaging_unit_name'],
                'unique_together': {('product', 'packaging_unit_name')},
            },
        ),
    ]
