# Generated by Django 4.2.27 on 2026-01-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_product_base_unit_alter_product_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustmentrequest',
            name='adjustment_type',
            field=models.CharField(choices=[('quantity', '数量调整'), ('price', '单价调整'), ('both', '数量+单价调整'), ('unit', '单位调整')], default='quantity', max_length=20, verbose_name='调整类型'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentrequest',
            name='conversion_factor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='转换系数（新数量=旧数量×系数）'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentrequest',
            name='new_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='新单位（单位调整）'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale_out', '销售出库'), ('production_out', '生产领料出库'), ('production_in', '生产完工入库'), ('purchase_in', '采购入库'), ('adjustment', '库存调整'), ('unit_change', '单位调整')], max_length=20, verbose_name='变动类型'),
        ),
    ]
