# Generated by Django 4.2.27 on 2026-02-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_add_adjustment_type_and_unit_change_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='unit',
        ),
    ]
