# Generated by Django 4.2.27 on 2026-02-07 09:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_inventory_other_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemunitconversion',
            options={'ordering': ['content_type', 'created_at'], 'verbose_name': '单位换算', 'verbose_name_plural': '单位换算'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='other_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='其它物品单价'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='locked_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='锁定数量（基础单位）'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量（基础单位）'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='批次单价（基础单位）'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='用量'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_units', to='inventory.unit', verbose_name='用量单位'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量（基础单位）'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentrequest',
            name='adjust_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='调整数量（基础单位）'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentrequest',
            name='adjust_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='调整单价（基础单位）'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentrequest',
            name='current_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当前数量（基础单位）'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentrequest',
            name='current_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='当前单价（基础单位）'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentrequest',
            name='new_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='调整后数量（基础单位）'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentrequest',
            name='new_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='调整后单价（基础单位）'),
        ),
        migrations.AlterField(
            model_name='itemunitconversion',
            name='base_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_base_units', to='inventory.unit', verbose_name='换算基准单位'),
        ),
        migrations.AlterField(
            model_name='itemunitconversion',
            name='content_type',
            field=models.CharField(choices=[('material', '原料'), ('product', '成品')], max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='itemunitconversion',
            name='factor',
            field=models.DecimalField(decimal_places=6, help_text='1 目标单位 = 系数 × 基础单位。例：1吨=1000kg，系数为1000', max_digits=15, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='换算系数'),
        ),
        migrations.AlterField(
            model_name='itemunitconversion',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认显示换算'),
        ),
        migrations.AlterField(
            model_name='itemunitconversion',
            name='target_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_target_units', to='inventory.unit', verbose_name='换算目标单位'),
        ),
        migrations.AlterField(
            model_name='material',
            name='safety_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='安全库存（基础单位）'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价（基础单位）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='safety_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='安全库存（基础单位）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价（基础单位）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基础单价（基础单位）'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='base_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='系统自动换算后的基础单位量，用于库存增减', max_digits=10, null=True, verbose_name='基础单位数量'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='操作数量（操作单位）'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.unit', verbose_name='操作单位'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='简写符号'),
        ),
    ]
