# Generated by Django 4.2.27 on 2026-03-01 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_item_conversion_master_product'),
        ('inventory', '0025_product_material_master_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemunitconversion',
            name='master_product',
            field=models.ForeignKey(blank=True, help_text='与 product/material 二选一，供物料主数据（product.Product）使用', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_unit_conversions', to='product.product', verbose_name='产品主数据'),
        ),
    ]
