# Generated by Django 4.2.27 on 2026-03-01 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_item_conversion_master_product'),
        ('inventory', '0027_fill_item_conversion_master_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_master',
            field=models.ForeignKey(blank=True, help_text='成品/原料库存优先引用产品主数据；与 product/material 二选一或同时存在（同步用）', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='product.product', verbose_name='产品主数据'),
        ),
    ]
