# Generated by Django 4.2.27 on 2026-03-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_fill_inventory_product_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemunitconversion',
            name='content_type',
            field=models.CharField(choices=[('material', '原料'), ('product', '成品'), ('other', '其他')], max_length=20, verbose_name='类型'),
        ),
        migrations.AddConstraint(
            model_name='itemunitconversion',
            constraint=models.UniqueConstraint(condition=models.Q(('content_type', 'other')), fields=('master_product', 'target_unit'), name='unique_other_master_target_unit'),
        ),
    ]
